// The 30 stations of the Yamanote Line (山手線), in JY-number order.
// Inner loop runs in ascending JY order; outer loop descends.
// The line is circular: after JY30 (Yūrakuchō) comes JY01 (Tōkyō).
window.YAMANOTE_STATIONS = [
  { jy: "01", name: "Tōkyō",            kanji: "東京",   audio: { inner: "uploads/inner-JY01-Tokyo.opus",      outer: "uploads/outer-JY01-Tokyo.opus" } },
  { jy: "02", name: "Kanda",            kanji: "神田",   audio: { inner: "uploads/inner-JY02-Kanda.opus",      outer: "uploads/outer-JY02-Kanda.opus" } },
  { jy: "03", name: "Akihabara",        kanji: "秋葉原", audio: { inner: "uploads/inner-JY03-Akihabara.opus",    outer: "uploads/outer-JY03-Akihabara.opus" } },
  { jy: "04", name: "Okachimachi",      kanji: "御徒町", audio: { inner: "uploads/inner-JY04-Okachimachi.opus",  outer: "uploads/outer-JY04-Okachimachi.opus" } },
  { jy: "05", name: "Ueno",             kanji: "上野", audio: { inner: "uploads/inner-JY05-Ueno.opus",         outer: "uploads/outer-JY05-Ueno.opus" } },
  { jy: "06", name: "Uguisudani",       kanji: "鶯谷", audio: { inner: "uploads/inner-JY06-Uguisudani.opus",   outer: "uploads/outer-JY06-Uguisudani.opus" } },
  { jy: "07", name: "Nippori",          kanji: "日暮里", audio: { inner: "uploads/inner-JY07-Nippori.opus",      outer: "uploads/outer-JY07-Nippori.opus" } },
  { jy: "08", name: "Nishi-Nippori",    kanji: "西日暮里", audio: { inner: "uploads/inner-JY08-Nishi-Nippori.opus", outer: "uploads/outer-JY08-Nishi-Nippori.opus" } },
  { jy: "09", name: "Tabata",           kanji: "田端", audio: { inner: "uploads/inner-JY09-Tabata.opus",       outer: "uploads/outer-JY09-Tabata.opus" } },
  { jy: "10", name: "Komagome",         kanji: "駒込", audio: { inner: "uploads/inner-JY10-Komagome.opus",     outer: "uploads/outer-JY10-Komagome.opus" } },
  { jy: "11", name: "Sugamo",           kanji: "巣鴨", audio: { inner: "uploads/inner-JY11-Sugamo.opus",       outer: "uploads/outer-JY11-Sugamo.opus" } },
  { jy: "12", name: "Ōtsuka",           kanji: "大塚", audio: { inner: "uploads/inner-JY12-Otsuka.opus",       outer: "uploads/outer-JY12-Otsuka.opus" } },
  { jy: "13", name: "Ikebukuro",        kanji: "池袋", audio: { inner: "uploads/inner-JY13-Ikebukuro.opus",    outer: "uploads/outer-JY13-Ikebukuro.opus" } },
  { jy: "14", name: "Mejiro",           kanji: "目白", audio: { inner: "uploads/inner-JY14-Mejiro.opus",       outer: "uploads/outer-JY14-Mejiro.opus" } },
  { jy: "15", name: "Takadanobaba",     kanji: "高田馬場", audio: { inner: "uploads/inner-JY15-Takadanobaba.opus", outer: "uploads/outer-JY15-Takadanobaba.opus" } },
  { jy: "16", name: "Shin-Ōkubo",       kanji: "新大久保", audio: { inner: "uploads/inner-JY16-Shin-Okubo.opus",   outer: "uploads/outer-JY16-Shin-Okubo.opus" } },
  { jy: "17", name: "Shinjuku",         kanji: "新宿", audio: { inner: "uploads/inner-JY17-Shinjuku.opus",     outer: "uploads/outer-JY17-Shinjuku.opus" } },
  { jy: "18", name: "Yoyogi",           kanji: "代々木", audio: { inner: "uploads/inner-JY18-Yoyogi.opus",       outer: "uploads/outer-JY18-Yoyogi.opus" } },
  { jy: "19", name: "Harajuku",         kanji: "原宿", audio: { inner: "uploads/inner-JY19-Harajuku.opus",     outer: "uploads/outer-JY19-Harajuku.opus" } },
  { jy: "20", name: "Shibuya",          kanji: "渋谷", audio: { inner: "uploads/inner-JY20-Shibuya.opus",      outer: "uploads/outer-JY20-Shibuya.opus" } },
  { jy: "21", name: "Ebisu",            kanji: "恵比寿", audio: { inner: "uploads/inner-JY21-Ebisu.opus",        outer: "uploads/outer-JY21-Ebisu.opus" } },
  { jy: "22", name: "Meguro",           kanji: "目黒", audio: { inner: "uploads/inner-JY22-Meguro.opus",       outer: "uploads/outer-JY22-Meguro.opus" } },
  { jy: "23", name: "Gotanda",          kanji: "五反田", audio: { inner: "uploads/inner-JY23-Gotanda.opus",      outer: "uploads/outer-JY23-Gotanda.opus" } },
  { jy: "24", name: "Ōsaki",            kanji: "大崎", audio: { inner: "uploads/inner-JY24-Osaki.opus",        outer: "uploads/outer-JY24-Osaki.opus" } },
  { jy: "25", name: "Shinagawa",        kanji: "品川", audio: { inner: "uploads/inner-JY25-Shinagawa.opus",    outer: "uploads/outer-JY25-Shinagawa.opus" } },
  { jy: "26", name: "Takanawa Gateway", kanji: "高輪ゲートウェイ", audio: { inner: "uploads/inner-JY26-TakanawaGateway.opus", outer: "uploads/outer-JY26-TakanawaGateway.opus" } },
  { jy: "27", name: "Tamachi",          kanji: "田町", audio: { inner: "uploads/inner-JY27-Tamachi.opus",      outer: "uploads/outer-JY27-Tamachi.opus" } },
  { jy: "28", name: "Hamamatsuchō",     kanji: "浜松町", audio: { inner: "uploads/inner-JY28-Hamamatsucho.opus", outer: "uploads/outer-JY28-Hamamatsucho.opus" } },
  { jy: "29", name: "Shimbashi",        kanji: "新橋", audio: { inner: "uploads/inner-JY29-Shimbashi.opus",    outer: "uploads/outer-JY29-Shimbashi.opus" } },
  { jy: "30", name: "Yūrakuchō",        kanji: "有楽町", audio: { inner: "uploads/inner-JY30-Yurakucho.opus", outer: "uploads/outer-JY30-Yurakucho.opus" } },
];
