// The 30 stations of the Yamanote Line (山手線), in JY-number order.
// Inner loop runs in ascending JY order; outer loop descends.
// The line is circular: after JY30 (Yūrakuchō) comes JY01 (Tōkyō).
window.YAMANOTE_STATIONS = [
  { jy: "01", name: "Tōkyō",            kanji: "東京",   audio: { inner: "uploads/inner-JY01-Tokyo.opus",      outer: "uploads/outer-JY01-Tokyo.opus" } },
  { jy: "02", name: "Kanda",            kanji: "神田",   audio: { inner: "uploads/inner-JY02-Kanda.opus",      outer: "uploads/outer-JY02-Kanda.opus" } },
  { jy: "03", name: "Akihabara",        kanji: "秋葉原" },
  { jy: "04", name: "Okachimachi",      kanji: "御徒町" },
  { jy: "05", name: "Ueno",             kanji: "上野" },
  { jy: "06", name: "Uguisudani",       kanji: "鶯谷" },
  { jy: "07", name: "Nippori",          kanji: "日暮里" },
  { jy: "08", name: "Nishi-Nippori",    kanji: "西日暮里" },
  { jy: "09", name: "Tabata",           kanji: "田端" },
  { jy: "10", name: "Komagome",         kanji: "駒込" },
  { jy: "11", name: "Sugamo",           kanji: "巣鴨" },
  { jy: "12", name: "Ōtsuka",           kanji: "大塚" },
  { jy: "13", name: "Ikebukuro",        kanji: "池袋" },
  { jy: "14", name: "Mejiro",           kanji: "目白" },
  { jy: "15", name: "Takadanobaba",     kanji: "高田馬場" },
  { jy: "16", name: "Shin-Ōkubo",       kanji: "新大久保" },
  { jy: "17", name: "Shinjuku",         kanji: "新宿" },
  { jy: "18", name: "Yoyogi",           kanji: "代々木" },
  { jy: "19", name: "Harajuku",         kanji: "原宿" },
  { jy: "20", name: "Shibuya",          kanji: "渋谷" },
  { jy: "21", name: "Ebisu",            kanji: "恵比寿" },
  { jy: "22", name: "Meguro",           kanji: "目黒" },
  { jy: "23", name: "Gotanda",          kanji: "五反田" },
  { jy: "24", name: "Ōsaki",            kanji: "大崎" },
  { jy: "25", name: "Shinagawa",        kanji: "品川" },
  { jy: "26", name: "Takanawa Gateway", kanji: "高輪ゲートウェイ" },
  { jy: "27", name: "Tamachi",          kanji: "田町" },
  { jy: "28", name: "Hamamatsuchō",     kanji: "浜松町" },
  { jy: "29", name: "Shimbashi",        kanji: "新橋" },
  { jy: "30", name: "Yūrakuchō",        kanji: "有楽町", audio: { inner: "uploads/inner-JY30-Yurakucho.opus", outer: "uploads/outer-JY30-Yurakucho.opus" } },
];
